AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Create Salesforce DB Secret"

Parameters:
  KmsKeyId:
    Type: String

Resources:

  MNGeoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'medss/medss_crm_user'
      Description: 'Salesforce OData DB Secret'
      KmsKeyId: !Ref KmsKeyId
      SecretString: '{"password":"changeme","username":"covidsalesforce_user"}'

