AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Create Salesforce Client Secret"

Parameters:
  KmsKeyId:
    Type: String

Resources:

  MNGeoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'medss_salesforce_client'
      Description: 'Salesforce OData Client Secret'
      KmsKeyId: !Ref KmsKeyId
      SecretString: '{"password":"changeme","username":"sf-crm-api-client"}'

