server:
  port: 8080

spring:
  jersey:
    application-path: /odata

#  datasource:
#    url: jdbc:awsathena://athena.us-east-2.amazonaws.com:443/medssdev_curated?max_error_retries=20&connection_timeout=20000;S3OutputLocation=s3://aws-athena-query-results-us-east-2-938619397650;AwsCredentialsProviderClass=com.simba.athena.amazonaws.auth.DefaultAWSCredentialsProviderChain
#    driver-class-name: com.simba.athena.jdbc.Driver

  datasource:
    #url: jdbc-secretsmanager:postgresql://medssdevreporting.cyznv5hu7wjv.us-east-2.rds.amazonaws.com/medss_dev
    #url: jdbc-secretsmanager:postgresql://medssproductionreporting.cqlpwu3nasvo.us-east-2.rds.amazonaws.com/medss_prod
    #url: jdbc-secretsmanager:postgresql://medssproductionreplica2.cqlpwu3nasvo.us-east-2.rds.amazonaws.com/medss_prod
    url: jdbc-secretsmanager:postgresql://covid-salesforce.cluster-cyznv5hu7wjv.us-east-2.rds.amazonaws.com/covidsalesforce
    username: covidsalesforce/rds/covidsalesforce_user
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    maximum-pool-size: 10
    minimum-idle: 2

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

secret:
  region: us-east-2
  name: medss_salesforce_client
